# This file was auto-generated by cabal2nix. Please do NOT edit manually!
{ haskellPackages ? (import <nixpkgs> {}).haskellPackages }:
let 
  inherit (haskellPackages) cabal heist lens MonadCatchIOTransformers mtl snap snapCore
  snapLoaderStatic snapServer text time xmlhtml snapletPostgresqlSimple postgresqlSimple transformers
  ;

in cabal.mkDerivation (self: {
  pname = "projectomatic";
  version = "0.1";
  src = ./.;
  isLibrary = false;
  isExecutable = true;
  buildDepends = [
    heist lens MonadCatchIOTransformers mtl snap snapCore
    snapLoaderStatic snapServer text time xmlhtml snapletPostgresqlSimple postgresqlSimple transformers
  ];
  meta = {
    description = "Project Synopsis Here";
    license = self.stdenv.lib.licenses.unfree;
    platforms = self.ghc.meta.platforms;
  };
})
